### ISSUE TITLE
Remove use of deprecated gtk_timeout_add etc

### ISSUE THREAD

**Issue by oskarb** [GnoTime/gnotime#19]
gtk_timeout_add() and related has allegedly been deprecated since GTK 2.4.

Looks like the replacement is g_timeout_add() but I have not researched it fully.

**Comment by oskarb** [comment]
Our timer callback (now I am looking in journal.c) returns 0, which mean the timer (i.e. event source) is automatically removed.

Additionally, the current code uses gtk_timeout_remove - internally this corresponds to g_source_remove, which also seems to be the way to cancel a timeout created using g_timeout_add.

But documentation says it's an error to attempt remove a source that has already been removed and a runtime warning is issued:

    (gnotime:8457): GLib-CRITICAL **: Source ID 1284 was not found when attempting to remove it

It's an error because the source id may in fact have been reused. See https://docs.gtk.org/glib/type_func.Source.remove.html.

In e.g. journal.c hover_timer_func, before the callback returns 0 to auto-destroy the timer, it should probably also clear `wig->hover_timeout_id` to avoid other attempts at removing the source.

**Comment by markuspg** [comment]
Is this still relevant or is it completed with the merge of #20? At least grepping for `gtk_timeout` does not produce any results :-)
