### ISSUE TITLE
Use GSettings for configuration

### ISSUE THREAD

**Issue by markuspg** [GnoTime/gnotime#3]
Replace all usages of _GConf_ by _GSettings_ and drop _GConf_ from the project entirely.

**Comment by markuspg** [comment]
The introduction of configuration handling based on _GSettings_ has been completed with #31.

**Comment by oskarb** [comment]
As mentioned above, GSettings is now the configuration storage mechanism. GConf is still used "read-once" to import existing settings on upgrade.
