### ISSUE TITLE
Infinite recursion until segfault starting timer after -DGSEAL_ENABLE

### ISSUE THREAD

**Issue by oskarb** [GnoTime/gnotime#43]
Commit 3c19c4c0 enabled compilation with -DGSEAL_ENABLE, which required some changes. Following these changes, it's impossible to start the timer. Trying to do so results in infinite recursion and eventually segfault.

The cause is this change in menus.c:
https://github.com/GnoTime/gnotime/commit/3c19c4c0d2c3e0fa62f187acb957e7707595dfa4#diff-ad990f8c2d8bd10fd16c3a68e26e1c003fe3f6609b8abfd508422cf9096b7577R285-R290

In fact, the comment already in place there explains what happens.

CC @markuspg

**Comment by markuspg** [comment]
I merged this by accident with #38. I'm currently pondering how to fix it. I guess my attempt would be to disconnect the signal causing the infinite loop before adjusting the `active` state of the respective widget and re-connecting it after the adjustment. I tried to find if there is the possibility to temporarily silence a signal, but I could not find such.

**Comment by oskarb** [comment]
For blocking a signal *handler*, there is https://docs.gtk.org/gobject/func.signal_handler_block.html. But I think that not necessarily the right approach.

The handler should be `menu_toggle_timer()` ([code](https://github.com/GnoTime/gnotime/blob/e15e51fac39347b46a759df00747806875a5d2e1/src/menucmd.c#L359C1-L372)). I think the issue might be considered to be the fact that this method doesn't care about the state of the menu item. It only checks `timer_is_running()`, which is based on if timer.c has a "cur_proj" or not. So if the menu was toggled, the handler assumes that if a project is running, it should be stopped.

I think the handler should instead consider the state of the menu item after the toggle action and interpret this state as the desired state. So if the item was toggled *to* active mode, and a project already is active, there is nothing to do, and vice versa. 

I will test it.
